---
services:
- docker

script:
# Execute Postman collection from URL
- docker run -t postman/newman run "https://www.getpostman.com/collections/8a0c9bc08f062d12dcda"
# Execute Postman collection from directory
- docker run -v `pwd`/collections:/etc/newman -t postman/newman run httpbin-example.json.postman_collection